//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public int ArticleID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedByUserID { get; set; }
        public string Text { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual User User { get; set; }
    }
}
