USE [BlogDB]
GO

/****** Object:  Table [dbo].[Comments]    Script Date: 2013.08.10. 12:51:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TagsInArticles'))
	BEGIN
		DROP TABLE [dbo].[TagsInArticles]
	END

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Comments'))
	BEGIN
		DROP TABLE [dbo].[Comments]
	END

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Articles'))
	BEGIN
		DROP TABLE [dbo].[Articles]
	END

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Tags'))
	BEGIN
		DROP TABLE [dbo].[Tags]
	END

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Users'))
	BEGIN
		DROP TABLE [dbo].[Users]
	END