USE [BlogDB]
GO

SET IDENTITY_INSERT [dbo].[Articles] ON

INSERT INTO [dbo].[Articles] ([ID], [Title] ,[CreateDate] ,[CreatedByUserID] ,[Text]) VALUES (1, 'Drog miatt állítottak elõ hét fiatalt a Szigeten', GETDATE(), 1, 'A 21. Sziget Fesztiválon pénteken, illetve szombat hajnalban a Budapesti Rendõr-fõkapitányság munkatársai több személlyel szemben intézkedtek - olvasható a police.hu-n. Összesen hét személyt állítottak elõ, akiknél az ellenõrzések során kábítószergyanús anyagokat találtak. Az elõállítottak közül hat fõ külföldi állampolgár. Az elfogott és elõállított gyanúsítottak közül egy személyt õrizetbe vettek. Mindannyiuk ellen kábítószer terjesztés megalapozott gyanúja miatt indított eljárást a Budapesti Rendõr-fõkapitányság III. Kerületi Rendõrkapitánysága. A rendõrség arról is beszámolt, hogy két szlovák, illetve két magyar fiatal ellen lopás miatt indult eljárás. A rendelkezésre álló adatok szerint õket hajnalban érték tetten, amikor a fesztivál campingjében felállított sátrakból különbözõ értékeket tulajdonítottak el.')
INSERT INTO [dbo].[Articles] ([ID], [Title] ,[CreateDate] ,[CreatedByUserID] ,[Text]) VALUES (2, 'A fuldokló kisfiún segítõ nõt is elragadta a Tisza',  GETDATE(), 2, 'A 8 év körüli gyermeket Aranyosapátinál ragadta el a folyó, majd a segítségére sietõ nõ is elmerült. A gyermek élettelen testét megtalálták, a nõt még keresik a helyszínre érkezett tûzoltók és speciális mentõk.')
INSERT INTO [dbo].[Articles] ([ID], [Title] ,[CreateDate] ,[CreatedByUserID] ,[Text]) VALUES (3, 'Elkapták a pólórabló tiniket',  GETDATE(), 1, 'A Budaörsi Rendõrkapitányság Bûnügyi Osztálya eljárást indított csoportosan elkövetett rablás bûntettének megalapozott gyanúja miatt két 17 éves és egy 13 éves piliscsabai fiú ellen - közölte a rendõrség a police.hu-n. A jelenleg rendelkezésre álló adatok szerint a fiatalok még augusztus 2-án 20 óra körül Piliscsabán feltartóztattak két fiatalt az utcán és az egyiküket bántalmazással fenyegették, ha nem adja nekik a rajta lévõ pólót. Mikor távoztak, megfenyegették a két fiatalt, hogy amennyiben szólnak a bûncselekményrõl, akkor bántódásuk fog esni. A pontos személyleírás és a begyûjtött adatok alapján a budaörsi rendõrök augusztus 8-án elfogták és a Budaörsi Rendõrkapitányságra elõállították a bûncselekménnyel gyanúsítható két 17 éves fiatalt. Harmadik társukat –aki 14. életévét még nem töltötte be–, másnap szintén kihallgatták. A július 1-jén hatályba lépett új Büntetõ Törvénykönyv szerint már neki is felelnie kell tettéért e bûncselekmény tekintetében.')
INSERT INTO [dbo].[Articles] ([ID], [Title] ,[CreateDate] ,[CreatedByUserID] ,[Text]) VALUES (4, 'A nemzetbiztonsági bizottság is rámenne a romagyilkosságok ügyére',  GETDATE(), 1, 'A parlament nemzetbiztonsági bizottsága is vizsgálhatja, hogy milyen szerepe volt az egykori Katonai Biztonsági Hivatalnak (KBH) a romagyilkosságok késedelmes feltárásában - írja a szombati Magyar Nemzet. A vizsgálat szükségességét Gulyás József, a testület egykori SZDSZ-es tagja, a gyilkosságok titkosszolgálati hátterét 2009-ben vizsgáló munkacsoport vezetõje vetette fel a lapnak nyilatkozva. A szakértõ szerint fontos megvizsgálni, hogy Csontos István negyedrendû vádlottról, akirõl kiderült, hogy a KBH titkos kapcsolata volt, mit írt le a tartótisztje, és milyen jelentések készültek arról az ismert és nem ismert debreceni körrõl, amely a romák elleni támadásokban érintett lehetett.')

SET IDENTITY_INSERT [dbo].[Articles] OFF
GO


